# Generated script for Pub-Synonymous - Run 1
# Generated on: 2025-11-13T17:05:39.651488
# Model: meta-llama/Llama-3.1-8B-Instruct

```python
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from scipy.cluster.hierarchy import linkage, fcluster
from scipy.cluster.hierarchy import dendrogram
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import fclusterdata
from scipy.cluster.hierarchy import fcluster
from